apiVersion: apps/v1
kind: Deployment
metadata:
  name: oranges
  labels:
    app: oranges
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oranges
  template:
    metadata:
      labels:
        app: oranges
    spec:
      containers:
        - name: nginx
          image: quay.io/ysachin/ocp-exam
          imagePullPolicy: IfNotPresent   # <-- Yeh line add kar di maine
          ports:
            - containerPort: 80

